### ISSUE TITLE
Issue Template

### ISSUE THREAD

**Issue by stevenpeniche** [tdfranklin/newtons-apple#6]
Setting up an **issue template** would benefit issue readability and enhance the workflow of this project.

**Comment by tdfranklin** [comment]
@stevenpeniche 
Was just looking over issues to try and get them cleared off... you have any ideas for this?  I think it's a great idea and I'll try and Google some good issue templates to see if we can implement one.  In the meantime, if you have any ideas, feel free to post here and we can implement.

**Comment by stevenpeniche** [comment]
I’ll take the same route as you. Google and see what best fits Newton’s Apple.

**Comment by stevenpeniche** [comment]
For now we can go with the basic structure proposed [here](https://help.github.com/articles/creating-an-issue-template-for-your-repository/). Later on if we feel it needs to be more robust then we'll add to it.

**Comment by tdfranklin** [comment]
Resolved with PR #22
