### ISSUE TITLE
Pull Request Template

### ISSUE THREAD

**Issue by stevenpeniche** [tdfranklin/newtons-apple#7]
Setting up a **pull request template** would benefit PR readability and enhance the workflow of this project.

**Comment by tdfranklin** [comment]
@stevenpeniche 
Same here as with issue template... any ideas?

**Comment by stevenpeniche** [comment]
Going to google and see what best fits Newton’s Apple.

**Comment by stevenpeniche** [comment]
Once again we can go with the basic structure proposed [here](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/). Later on if we feel it needs to be more robust then we'll add to it.

**Comment by tdfranklin** [comment]
Resolved with PR #22
